Pass in debug_mem_usage to avoid mem_pool allocation at the beginning when debug_mem_usage=true (haog/gqe-python!166)
### Pass in debug_mem_usage to avoid mem_pool allocation at the beginning when debug_mem_usage=true

**During table loading** (first 3 calls with false): When you call catalog.register_tpch(), it loads each table into memory.

```
    context ctx(1,
                num_row_groups,
                in_memory_table_compression_format,
                in_memory_table_compression_data_type,
                compression_chunk_size,
                zone_map_partition_size);
    ctx.execute(catalog, write_table, std::nullopt);
```

**During query execution context creation**, when building the actual query execution context:

```
context = Context(*context_params, debug_mem_usage=debug_mem_usage)
```

The log looks like the below, the context constructor is using its default value of false for the debug_mem_usage parameter during table loading.

This change is mainly to fix after [MR!150](https://gitlab-master.nvidia.com/haog/gqe-python/-/merge_requests/150) was merged which makes the memory pool static. With a static pool, the first context creation (during table loading) locks in the memory resource type for all subsequent contexts.

```
Running query from handcoded with parameters debug_mem_usage=True, QueryExecutionContext(num_workers=1, num_partitions=4, use_overlap_mtx=False, join_use_hash_map_cache=False, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=True, join_use_mark_join=False, use_partition_pruning=False, filter_use_like_shift_and=False, aggregation_use_perfect_hash=False, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=18, query_str='18', query_source='handcoded', reference_file='/solution_100/q18.parquet', scale_factor=100.0, substrait_file=None, physical_plan_folder=None)), DataInfo(num_row_groups=1, compression_format='none', compression_data_type='char', compression_chunk_size=65536, zone_map_partition_size=100000, data_info_id=1, storage_device_kind='pinned_memory', format='internal', location=None, not_null=False, identifier_type='TypeId.int32', char_type='char', decimal_type='float')
Attempting to load TPCH Query 18 data into memory
[2025-10-24 18:41:55.395] [gqe] [info] Debug memory usage: false
[2025-10-24 18:41:57.221] [gqe] [info] Debug memory usage: false
[2025-10-24 18:41:57.446] [gqe] [info] Debug memory usage: false
Building query execution context...
[2025-10-24 18:41:57.498] [gqe] [info] Debug memory usage: true
Running Q18...
Starting query Q18 repetition 0...
Error during query execution
MemoryError: std::bad_alloc: out_of_memory: CUDA error (failed to allocate 4800303216 bytes) at: /conda/envs/gqe/include/rmm/mr/device/cuda_async_view_memory_resource.hpp:102: cudaErrorMemoryAllocation out of memory
```