Fix partial filters for fused filter operations (haog/gqe-python!167)
## Description

Fix `ReadRelation.partial_filter` without relying on the parent `FilterRelation` when `load_all_data = 0`.

Fixes https://gitlab-master.nvidia.com/haog/gqe-python/-/issues/19

## Solved problem

When fixing a `ReadRelation.partial_filter`, `fix_partial_filter_column_references` relies on the existence of a parent `FilterRelation`. However, Q10_opt fuses the `FilterRelation` into a custom join probe operator. The plan reads `lineitem` with a partial filter but there is no expected `FilterRelation`. When partition pruning is enabled and `load_all_data = 0`, this triggers an error during the evaluation of the partial filter.

```
Error during query execution
IndexError: vector::_M_range_check: __n (which is 16) >= this->size() (which is 8)
```