fix record-not-found error after restarting from unrecoverable error (haog/gqe-python!268)
# Issue

```
Parameter sets remaining: 919
[2026-02-25 23:41:43.431] [gqe] [error] cudaHostUnregister failed with: an illegal memory access was encountered
[2026-02-25 23:41:43.985] [gqe] [error] cudaHostUnregister failed with: an illegal memory access was encountered
/gqe/src/libperfect/memory_pool.cpp:111: GPUassert: an illegal memory access was encountered
terminate called after throwing an instance of 'std::logic_error'
  what():  /gqe/src/libperfect/memory_pool.cpp:111: GPUassert: an illegal memory access was encountered
Data load stage ended after 3.00s
Subprocess exited with non-zero return code with 919 tasks remaining.
Subprocess Exit Code -6
Subprocess may have been killed by SIGABRT
Starting parameter set execution with 919 sets remaining
Using 300s query timeout and 3000s data load timeout
Parameter sets remaining: 919
Attempting to load full TPC-H dataset into memory
Running query from handcoded with parameters debug_mem_usage=False, QueryExecutionContext(num_workers=2, num_partitions=8, use_overlap_mtx=False, join_use_hash_map_cache=False, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=True, jo
in_use_mark_join=False, use_partition_pruning=False, filter_use_like_shift_and=False, aggregation_use_perfect_hash=True, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=10, query_str='10', query_source='handcoded', reference_file='/solution/q10.par
quet', scale_factor=100.0, substrait_file=None, physical_plan_folder=None)), DataInfo(num_row_groups=4, compression_format='ans', compression_chunk_size=131072, zone_map_partition_size=200000, compression_ratio_threshold=1.0, secondary_compression_format='casc
aded', secondary_compression_ratio_threshold=1.0, secondary_compression_multiplier_threshold=1.0, use_cpu_compression=False, compression_level=10, data_info_id=1, storage_device_kind='numa_pinned_memory', format='internal', location=None, not_null=False, ident
ifier_type='bigint', char_type='char', decimal_type='float', scale_factor=100.0)
No load required - data already in memory
Refreshing query execution context...
Data load stage ended after 20.04s
Context creation ended after 0.13s
Process SpawnProcess-152:
Traceback (most recent call last):
  File "/conda/envs/gqe/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/conda/envs/gqe/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gqe-python_fork/gqe/benchmark/run.py", line 475, in run_suite
    _run_suite(
  File "/gqe-python_fork/gqe/benchmark/run.py", line 772, in _run_suite
    edb.insert_gqe_column_stats(
  File "/gqe-python_fork/gqe/benchmark/gqe_experiment.py", line 191, in insert_gqe_column_stats
    return sql_generator.select_id(self._cursor, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda/envs/gqe/lib/python3.12/site-packages/database_benchmarking_tools/sql_generator.py", line 78, in select_id
    result = cursor.fetchone()[0]
             ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Query execution/validation iteration 0 ended after 3.00s
```

# Problem

After an unrecoverable CUDA error, the function returns early (the return in in run.py), shown below

```
                    if is_unrecoverable_error(error):
                        return
                    else:
                        break
```

On the next run:

1. Table/column stats are inserted before query execution (lines 755-799)
2. `insert_or_ignore` ignores the insert (unique key exists)
3. select_id() matches on all fields, not just the unique key since other column values differ due to reloading the data
4. If compression stats differ, select_id() returns None, causing `TypeError: 'NoneType' object is not subscriptable`

# Changes

1. gqe/benchmark/run.py (line 837)

   • Removed duplicate break statement (unreachable code)
2. gqe/benchmark/system_under_test.sql

   • add all columns as the unique key constraint for the `gqe_column_stats` table ( the reason is that there is a insert_or_ignore called by `insert_gqe_column_stats` which could insert many duplicate rows if there is no such constraint, so it's necessary to have such constraint.

# Testing

Test with a run that fails with an unrecoverable CUDA error, then rerun the same query

This change is backward compatible and only affects the error path.

### Example rows in gqe_column_stats after the change

```
cs_id|cs_gqe_table_stats_id|cs_column_name|cs_column_part|cs_compressed_bytes|cs_uncompressed_bytes|cs_compression_ratio|cs_slices|cs_compressed_slices|cs_primary_compressed_bytes|cs_secondary_compressed_bytes|cs_num_primary_compressed_slices|cs_num_secondary_compressed_slices
3381|312|c_mktsegment|char|68947952|135002670|1.95803741929855|1|1|68947952|116559076|1|0
3404|312|c_mktsegment|char|68947954|135002670|1.958037362501|1|1|68947954|116559076|1|0
3382|312|c_mktsegment|offset|7075892|60000000|8.47949629530807|1|1|46214250|7075892|0|1
3405|312|c_mktsegment|offset|7075892|60000000|8.47949629530807|1|1|46214252|7075892|0|1
3373|312|c_name|char|138533194|270000000|1.94899137314339|1|1|138533194|270057000|1|0
3402|312|c_name|offset|666000|60000000|90.0900900900901|1|1|47025860|666000|0|1
3374|312|c_name|offset|666000|60000000|90.0900900900901|1|1|47025868|666000|0|1
```