Add optimized implementation for TPC-H Q10 (haog/gqe-python!131)
Adds a new query plan, `10_opt`, with kernel fusion and other optimizations.

# Optimizations

* Reordering of joins to reduce cardinality of later operations
* Fused probe pipeline for two joins (`o_custkey = c_custkey` and `n_nationkey = c_nationkey`) to reduce unnecessary materializations
* Bloom filter for the join on `o_custkey = c_custkey` to reduce hash multimap lookup
* Combined `order by` and `limit` clauses to reduce unnecessary materializations
* Use of identity hash function in place of cuCo default

# Reusable components

* Unique-key inner join implemented in gqe-python
  * Limited to single join key but already reuseable for TPC-H queries; can be generalized as needed.
* Multimap-based hash join specialized for unique probe side
  * May be generalizable to GQE for hash joins where we would like to build on the smaller side while taking advantage of uniqueness property on the probe side to bound the output size (instead of having to compute the output size).

# Benchmark

Kernel time at SF1K on GB200 improves from 561 ms to 361 ms.

# Additional ideas

* Fuse the group-by aggregation into the probe pipeline to reduce yet another round of materializations (expensive due to multiple string columns). This requires a multi-key group-by implementation in gqe-python.
* Store the string columns in persistent objects for later reference, so that index columns can be passed among operators instead of the full string columns (up until the aggregation).
* In addition to the string columns, also store the hash values of the string elements so they do not have to be recomputed repeatedly during lookup.
* Fuse filter on `lineitem` table into `Q10UniqueKeyInnerJoinProbeRelation` to reduce materialization cost. An attempt was made on commit 30691de01648de09e720200bcd31910764e3bbb5, but runs into error when using SPP:

```
Error during query execution
IndexError: vector::_M_range_check: __n (which is 16) >= this->size() (which is 8)
```

* Combine `Q10UniqueKeyInnerJoinBuildRelation` and `Q10UniqueKeyInnerJoinProbeRelation` to prevent repeated concatenation of build-side table.

# To-do

* [x] Add "10_opt" to list of handcoded queries in `run_tpch_parameter_sweep.py`