Fix variable name bug (haog/gqe-python!69)
This MR fixes a bug introduced in MR https://gitlab-master.nvidia.com/haog/gqe-python/-/merge_requests/51. `run_tpch_e2e.py` fails with:

```sh
$ ./gqe/benchmark/run_tpch_e2e.py -- /scratch/local/sf1_id32 /home/gqe/tpch/substrait_plans /home/gqe/tpch/spark_results/sf1/%d.parquet
Traceback (most recent call last):
  File "/home/clutz/code/gqe-python/./gqe/benchmark/run_tpch_e2e.py", line 136, in <module>
    main()
  File "/home/clutz/code/gqe-python/./gqe/benchmark/run_tpch_e2e.py", line 65, in main
    identifier_type = parse_identifier_type(args.location)
                                            ^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'location'. Did you mean: 'solution'?
```

The MR also renames the argument `location` to `dataset` in `run_tpch.py`, to match the naming of `run_tpch_e2e.py`. This should prevent similar problems in future.